config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :tasks do
      resources :comments, only: [:create]
    end
    resources :memberships
  end
  resources :users

  root "pages#index"
  get 'about' => 'pages#about', as: :about
  get 'terms' => 'pages#terms', as: :terms
  get 'faq' => 'pages#faq', as: :faq

  get 'signup' => 'registrations#new', as: :signup
  post 'signup' => 'registrations#create'
  get 'signin' => 'authentication#new', as: :signin
  post 'signin' => 'authentication#create'
  get 'signout' => 'authentication#destroy', as: :signout

  get '/tracker_projects/:tracker_id' => 'projects#tracker_stories', as: :tracker_stories

end

app/models/membership.rb
class Membership < ActiveRecord::Base
  before_destroy :not_last_owner?

  belongs_to :project
  belongs_to :user

  validates :user_id, presence: true, uniqueness: {scope: :project_id,
    message: "has already been added"}

  def not_last_owner?
    if self.role == "Member" || project.memberships.where(role: "Owner").count > 1
      true #before_destroy will delete
    else
      false #before_destroy won't delete
    end
  end

end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_project
  before_action :check_membership, only: [:index]
  before_action :set_projects
  before_action :check_ownership, only: [:create, :update]

  def index
    @membership = Membership.new
  end

  def create
    @membership = Membership.new(membership_params)
    @membership.project = @project
    if @membership.save
      redirect_to project_memberships_path(@project), notice: "#{@membership.user.full_name} was added successfully."
    else
      render :index
    end
  end

  def update
    @membership = @project.memberships.find(params[:id])
    if @membership.update(membership_params)
      redirect_to project_memberships_path(@project), notice: "#{@membership.user.full_name} was updated successfully."
    else
      render :index
    end
  end

  def destroy
    @membership = @project.memberships.find(params[:id])
    if current_user.project_owner?(@project) || current_user.admin?
      if @membership.destroy
        redirect_to project_memberships_path(@project), notice: "#{@membership.user.full_name} was removed successfully."
      else
        flash.now[:alert] = "Unable to remove #{@membership.user.full_name}."
        render :index
      end
    elsif current_user == @membership.user
      if @membership.destroy
        redirect_to projects_path, notice: "Your membership was removed successfully."
      else
        flash.now[:alert] = "Unable to remove your membership."
        render :index
      end
    else
      raise AccessDenied
    end
  end

  private

    def set_project
      @project = Project.find(params[:project_id])
    end

    def membership_params
      params.require(:membership).permit(:user_id, :role)
    end
end

app/views/memberships/_form.html.erb
<div class="row">
  <div class="col-sm-6">
    <%= render "shared/errors", record: @membership %>
  </div>
</div>

<div class="row">
  <div class="col-sm-6">
    <div class="well">
      <div class="form-inline">
        <%= form_for [@project, @membership] do |f| %>
          <div class="form-group">
            <%= f.collection_select(:user_id, User.order(:first_name), :id, :full_name, {include_blank: "Please select a user"}, {class: "form-control"}) %>
          </div>
          <div class="form-group">
            <%= f.select(:role, ["Member", "Owner"], {}, {class: "form-control"}) %>
          </div>
          <%= f.submit "Add New Member", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<table class="table">
  <% @project.memberships.each do |membership| %>
    <%= form_for [@project, membership] do |f| %>
      <tr>
        <td class="col-sm-2"><%= link_to membership.user.full_name, user_path(membership.user) %></td>
        <td class="col-sm-2"><%= f.select(:role, ["Member", "Owner"], {}, {class: "form-control"}) %></td>
        <td class="col-sm-1"><%= f.submit "Update", class: "btn btn-primary" %></td>
        <% if membership.role == "Owner" %>
          <% if membership.not_last_owner? %>
            <td><%= link_to "", project_membership_path(@project, membership), method: :delete, data: { confirm: 'Are you sure?' }, class: "glyphicon glyphicon-remove" %></td>
          <% else %>
            <td><em>Unable to delete the last owner</em></td>
          <% end %>
        <% else %>
          <td><%= link_to "", project_membership_path(@project, membership), method: :delete, data: { confirm: 'Are you sure?' }, class: "glyphicon glyphicon-remove" %></td>
        <% end %>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/memberships/_readonly.html.erb
<div class="row">
  <div class="col-sm-6">
    <%= render "shared/errors", record: @membership %>
  </div>
</div>

<% @project.memberships.each do |membership| %>
  <div class="row">
    <div class="col-md-2">
      <%= link_to membership.user.full_name, user_path(membership.user) %>
    </div>
    <div class="col-md-2">
      <%= membership.role %>
      <% if current_user == membership.user %>
        <%= link_to "", project_membership_path(@project, membership), method: :delete, data: { confirm: 'Are you sure?' }, class: "glyphicon glyphicon-remove" %>
      <% end %>
    </div>
    <br><br>
  </div>
<% end %>

app/views/memberships/index.html.erb
<%= page_header "#{@project.name}: Manage Members" do %>
<% end %>

<ol class="breadcrumb">
  <li><%= link_to "Projects", projects_path %></li>
  <li><%= link_to @project.name, project_path(@project) %></li>
  <li class="active">Memberships</li>
</ol>

<% if current_user.project_owner?(@project) || current_user.admin? %>
  <%= render 'form' %>
<% else %>
  <%= render 'readonly' %>
<% end %>