config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :tasks do
      resources :comments, only: [:create]
    end
    resources :memberships
  end
  resources :users

  root "pages#index"
  get 'about' => 'pages#about', as: :about
  get 'terms' => 'pages#terms', as: :terms
  get 'faq' => 'pages#faq', as: :faq

  get 'signup' => 'registrations#new', as: :signup
  post 'signup' => 'registrations#create'
  get 'signin' => 'authentication#new', as: :signin
  post 'signin' => 'authentication#create'
  get 'signout' => 'authentication#destroy', as: :signout

  get '/tracker_projects/:tracker_id' => 'projects#tracker_stories', as: :tracker_stories

end

app/models/task.rb
class Task < ActiveRecord::Base

  belongs_to :project
  has_many :comments, dependent: :destroy

  validates :description, presence: true
  validate :date_check, on: :create

  #Task date can't be set to a date in the past
  def date_check
    if due_date.present? && due_date < Date.today
      errors.add(:due_date, "can't be before today")
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_project
  before_action :check_membership
  before_action :set_projects, except: [:destroy]
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @sort_ref = "incomplete"

    if params[:type] == "all"
      @tasks = @project.tasks
      @sort_ref = "all"
    else
      @tasks = @project.tasks.where(complete: false)
    end
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @comment = Comment.new
  end

  # GET /tasks/new
  def new
    @task = @project.tasks.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = @project.tasks.new(task_params)
    @task.complete = false #New task can't be complete by default

    respond_to do |format|
      if @task.save
        format.html { redirect_to project_task_path(@project, @task), notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to project_task_path(@project, @task), notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to project_tasks_path(@project), notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = @project.tasks.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:description, :complete, :due_date)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for [@project, @task] do |f| %>
  <div class="form-horizontal" role="form">
    <div class="form-group">
      <div class="col-sm-offset-1 col-sm-5">
        <%= render "shared/errors", record: @task %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-1">
        <%= f.label :description, :class => "control-label" %>
      </div>
      <div class="col-sm-5">
        <%= f.text_field :description, :class => "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-1">
        <%= f.label :due_date, :class => "control-label" %>
      </div>
      <div class="col-sm-2">
        <%= f.date_field :due_date, :class => "form-control" %>
      </div>
    </div>
    <% unless @task.created_at.nil? %>
      <div class="form-group">
        <div class="col-sm-offset-1 col-sm-2">
          <%= f.check_box :complete %> <%= f.label :complete %>
        </div>
      </div>
    <% end %>
    <div class="form-group">
      <div class="col-sm-offset-1 col-sm-2">
        <%= f.submit :class => "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<%= page_header "Edit task" do %>
<% end %>

<%= render 'form' %>

app/views/tasks/index.html.erb
<div class="page-header">
  <h1>
    Tasks for <%= @project.name %>
      <div class="pull-right">
        <small>
          <%= link_to_if @sort_ref == "incomplete", "All", project_tasks_path(type: "all") %> |
          <%= link_to_if @sort_ref == "all", "Incomplete", project_tasks_path(type: "incomplete") %>
        </small>
        <%= link_to "Create Task", new_project_task_path, class: "btn btn-primary" %>
      </div>
  </h1>
</div>

<ol class="breadcrumb">
  <li><%= link_to "Projects", projects_path %></li>
  <li><%= link_to @project.name, project_path(@project) %></li>
  <li class="active">Tasks</li>
</ol>

<table class="table">
  <thead>
    <tr>
      <th><h4>Description</h4></th>
      <th><h4>Complete</h4></th>
      <th><h4>Due</h4></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td>
          <%= link_to task.description, project_task_path(@project, task) %>
          <div class="badge">
            <%= task.comments.count %>
          </div>
        </td>
        <td><%= task.complete.to_s.capitalize %></td>
        <td><%= task.due_date %></td>
        <td>
          <div class="pull-right">
            <%= link_to 'Edit', edit_project_task_path(@project, task), class: "btn btn-info" %>
            <%= link_to '', project_task_path(@project, task), method: :delete, data: { confirm: 'Are you sure?' }, class: "glyphicon glyphicon-remove" %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<%= page_header "New task" do %>
<% end %>

<%= render 'form' %>

app/views/tasks/show.html.erb
<%= page_header @task.description do %>
  <%= link_to "Edit", edit_project_task_path(@project, @task), class: "btn btn-info" %>
<% end %>

<ol class="breadcrumb">
  <li><%= link_to "Projects", projects_path %></li>
  <li><%= link_to @project.name, project_path(@project) %></li>
  <li><%= link_to "Tasks", project_tasks_path(@project) %></li>
  <li class="active">Show</li>
</ol>

<p>
  <strong>Due:</strong>
  <%= @task.due_date %>
</p>

<p>
  <strong>Complete:</strong>
  <%= @task.complete.to_s.capitalize %>
</p>

<h3>Comments</h3>
<% @task.comments.each do |comment| %>
  <div class="row">
    <div class="col-md-3">
      <% if comment.user.nil? %>
        <em>Deleted User</em>
      <% else %>
        <%= link_to comment.user.full_name, user_path(comment.user) %>
      <% end %>
      <div class="text-muted">
        <%= time_ago_in_words(comment.created_at).capitalize %> ago
      </div>
    </div>
    <div class="col-md-9">
      <%= comment.message %>
    </div>
  </div>
  <br>
<% end %>

<%= form_for [@project, @task, @comment] do |f| %>
<div class="form-horizontal">
  <div class="form-group">
    <div class="col-md-offset-3 col-md-9">
      <%= f.text_area :message, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-offset-3 col-md-9">
      <%= f.submit "Add Comment", class: "btn btn-primary" %>
    </div>
  </div>
</div>
<% end %>