config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :tasks do
      resources :comments, only: [:create]
    end
    resources :memberships
  end
  resources :users

  root "pages#index"
  get 'about' => 'pages#about', as: :about
  get 'terms' => 'pages#terms', as: :terms
  get 'faq' => 'pages#faq', as: :faq

  get 'signup' => 'registrations#new', as: :signup
  post 'signup' => 'registrations#create'
  get 'signin' => 'authentication#new', as: :signin
  post 'signin' => 'authentication#create'
  get 'signout' => 'authentication#destroy', as: :signout

  get '/tracker_projects/:tracker_id' => 'projects#tracker_stories', as: :tracker_stories

end

app/models/project.rb
class Project < ActiveRecord::Base

  has_many :tasks, dependent: :destroy
  has_many :memberships, dependent: :destroy

  validates :name, presence: true

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :set_projects, except: [:destroy]
  before_action :check_membership, only: [:show]
  before_action :check_ownership, only: [:edit, :update, :destroy]

  def index
    tracker_api = TrackerAPI.new
    @tracker_projects = tracker_api.projects(current_user.tracker_token)
  end

  def new
    @project = Project.new
  end

  def show
  end

  def edit
  end

  def tracker_stories
    tracker_api = TrackerAPI.new
    @tracker_project = tracker_api.project(params[:tracker_id], current_user.tracker_token)
    @tracker_stories = tracker_api.stories(params[:tracker_id], current_user.tracker_token)
  end

  def create
    @project = Project.new(project_params)
    @membership = Membership.new
    @membership.user = current_user
    @membership.role = "Owner"

    if @project.save
      @membership.project = @project
      if @membership.save
        redirect_to project_tasks_path(@project), notice: 'Project was successfully created.'
      else
        render :new
      end
    else
      render :new
    end
  end

  def update
    if @project.update(project_params)
      redirect_to project_path(@project), notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    #Sets all owners to members so before_destroy on
    #membership model won't stop the destroy
    @project.memberships.each do |membership|
      if membership.role == "Owner"
        membership.role = "Member"
      end
    end

    @project.destroy
    redirect_to projects_path, notice: 'Project was successfully destroyed.'
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name)
    end
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <div class="form-horizontal" role="form">
    <div class="form-group">
      <div class="col-sm-offset-1 col-sm-5">
        <%= render "shared/errors", record: @project %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-1">
        <%= f.label :name, :class => "control-label" %>
      </div>
      <div class="col-sm-5">
        <%= f.text_field :name, :class => "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-1 col-sm-2">
        <%= f.submit :class => "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/projects/edit.html.erb
<%= page_header "Edit project" do %>
<% end %>

<%= render 'form' %>

app/views/projects/index.html.erb
<%= page_header "Projects" do %>
  <%= link_to "Create Project", new_project_path, class: "btn btn-primary" %>
<% end %>

<table class="table">
  <thead>
    <tr>
      <th><h4>Name</h4></th>
      <th><h4>Members</h4></th>
      <th><h4>Tasks</h4></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project_path(project) %></td>
        <td><%= link_to project.memberships.count, project_memberships_path(project) %></td>
        <td><%= link_to project.tasks.count, project_tasks_path(project) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% unless current_user.tracker_token.nil? %>
  <div class="page-header">
    <h1>Pivotal Tracker Projects</h1>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th><h4>Name</h4></th>
      </tr>
    </thead>

    <tbody>
      <% @tracker_projects.each do |project| %>
        <tr>
          <td><%= link_to project[:name], tracker_stories_path(project[:id]) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/projects/new.html.erb
<%= page_header "Create project" do %>
<% end %>

<%= render 'form' %>

app/views/projects/show.html.erb
<%= page_header @project.name do %>
  <% if current_user.project_owner?(@project) || current_user.admin? %>
    <%= link_to 'Edit', edit_project_path(@project), class: "btn btn-primary" %>
  <% end %>
<% end %>

<ol class="breadcrumb">
  <li><%= link_to "Projects", projects_path %></li>
  <li class="active"><%= @project.name %></li>
</ol>

<p>
  <%= link_to pluralize(@project.tasks.count, 'Task'), project_tasks_path(@project) %>
</p>

<p>
  <%= link_to pluralize(@project.memberships.count, 'Member'), project_memberships_path(@project) %>
</p>

<% if current_user.project_owner?(@project) || current_user.admin? %>
  <div class="col-md-12 well">
    <p><strong>Delete Project</strong></p>
    <p>
      Deleting this project will also delete <%= pluralize(@project.memberships.count, 'membership') %>,
      <%= pluralize(@project.tasks.count, 'task') %> and associated comments.
    </p>
    <%= link_to "Delete", project_path(@project), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/projects/tracker_stories.html.erb
<%= page_header "Stories for #{@tracker_project[:name]}" do %>
  <strong>(showing first 500)</strong>
<% end %>

<table class="table table-striped table-bordered">
  <thead>
    <tr class="active">
      <th><h4>Story</h4></th>
      <th><h4>Estimate</h4></th>
      <th><h4>Labels</h4></th>
      <th><h4>Current State</h4></th>
    </tr>
  </thead>

  <tbody>
    <% @tracker_stories.each do |story| %>
      <tr>
        <td><%= link_to story[:name], story[:url] %></td>
        <td><%= story[:estimate] %></td>
        <td>
          <% labels = [] %>
          <% story[:labels].each do |label| %>
            <% labels << label[:name] %>
          <% end %>
          <%= labels.join", " %>
        </td>
        <td><%= story[:current_state].capitalize %></td>
      </tr>
    <% end %>
  </tbody>
</table>