config/routes.rb
Rails.application.routes.draw do

  resources :projects do
    resources :tasks do
      resources :comments, only: [:create]
    end
    resources :memberships
  end
  resources :users

  root "pages#index"
  get 'about' => 'pages#about', as: :about
  get 'terms' => 'pages#terms', as: :terms
  get 'faq' => 'pages#faq', as: :faq

  get 'signup' => 'registrations#new', as: :signup
  post 'signup' => 'registrations#create'
  get 'signin' => 'authentication#new', as: :signin
  post 'signin' => 'authentication#create'
  get 'signout' => 'authentication#destroy', as: :signout

  get '/tracker_projects/:tracker_id' => 'projects#tracker_stories', as: :tracker_stories

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><%= content_for(:title) || "gCamp" %></title>
    <%= stylesheet_link_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <%= link_to "gCamp", projects_path, class: "navbar-brand" %>
        </div>
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              My Projects
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <% @projects.each do |project| %>
                <li><%= link_to project.name, project_path(project) %>
              <% end %>
              <li class="divider"></li>
              <li><%= link_to "New Project", new_project_path %></li>
            </ul>
          </li>
        </ul>
        <ul class="nav navbar-nav">
          <li><%= link_to "Users", users_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li><%= link_to "#{current_user.full_name}", user_path(current_user) %></li>
            <li><%= link_to "Sign Out", signout_path %></li>
          <% else %>
            <li><%= link_to "Sign Up", signup_path %></li>
            <li><%= link_to "Sign In", signin_path %></li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="container">
      <% if notice %>
        <p class="alert alert-success text-center">
          <%= notice %>
        </p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger text-center">
          <%= alert %>
        </p>
      <% end %>
      <%= yield %>
      <hr>
      <footer class="text-center">
        <%= link_to_unless_current "Home", root_path %> |
        <%= link_to_unless_current "About", about_path %> |
        <%= link_to_unless_current "Terms", terms_path %> |
        <%= link_to_unless_current "FAQ", faq_path %>
      </footer>
    </div>
  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>gCamp</title>
    <%= stylesheet_link_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <% if current_user %>
            <%= link_to "gCamp", projects_path, class: "navbar-brand" %>
          <% else %>
            <%= link_to "gCamp", root_path, class: "navbar-brand" %>
          <% end %>
        </div>
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li><%= link_to "#{current_user.full_name}", user_path(current_user) %></li>
            <li><%= link_to "Sign Out", signout_path %></li>
          <% else %>
            <li><%= link_to "Sign Up", signup_path %></li>
            <li><%= link_to "Sign In", signin_path %></li>
          <% end %>
        </ul>
      </div>
    </div>

    <div class="container">
      <% unless notice.nil? %>
        <p id="notice" class="alert alert-success text-center">
          <%= notice %>
        </p>
      <% end %>
      <%= yield %>
      <hr>
      <footer>
        <%= link_to_unless_current "Home", root_path %> |
        <%= link_to_unless_current "About", about_path %> |
        <%= link_to_unless_current "Terms", terms_path %> |
        <%= link_to_unless_current "FAQ", faq_path %>
        <% if current_user %>
          | <%= link_to_unless_current "My Projects", projects_path %>
        <% end %>
        <div class="pull-right">
          <%= link_to "https://www.linkedin.com/in/joesiewert" do %>
            <%= image_tag "linked_in.png", width: "20em" %>
          <% end %>
          <%= link_to "https://github.com/joesiewert" do %>
            <%= image_tag "github.png", width: "20em" %>
          <% end %>
          <%= link_to "https://twitter.com/joesiewert" do %>
            <%= image_tag "twitter.png", width: "20em" %>
          <% end %>
          <%= link_to "http://www.galvanize.it/school#main" do %>
            <%= image_tag "gschool.png", width: "55em" %>
          <% end %>
        </div>
      </footer>
    </div>
  </body>
</html>